name: CD

on:
  push:
    branches: [ master ]

jobs:
send_email:
    runs-on: ubuntu-latest
    steps:
      - name: 发送邮件
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ secrets.EMAIL_TITLE }}
          body: ${{ secrets.EMAIL_BODY }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          content_type: text/html